# Generated by Django 2.1.2 on 2018-10-30 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProdList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('disc', models.TextField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='category')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('having', models.IntegerField(default=0)),
                ('havup', models.BooleanField(default=True)),
                ('creatime', models.DateTimeField(auto_now_add=True)),
                ('moditime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'ProdList',
                'db_table': 'ProdList',
            },
        ),
        migrations.CreateModel(
            name='ShopList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('disc', models.TextField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='category')),
            ],
            options={
                'verbose_name_plural': 'ShopList',
                'db_table': 'ShopList',
            },
        ),
        migrations.AddField(
            model_name='prodlist',
            name='typer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.ShopList'),
        ),
    ]
